name: Update docker-compose

on:
  push:
    branches:
      - main
  
jobs:
  config:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v2
      with:
        host: medconnect-ma.online
        private-key: ${{ secrets.SSH_KEY }}
  
    - name: Update docker-compose
      run: scp docker-compose.yml root@medconnect-ma.online:~/app

    - name: Copy .env.example
      run: scp .env.example
